# Generated by Django 2.2 on 2019-04-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('is_near_park', models.BooleanField(default=1)),
            ],
        ),
    ]
