# Generated by Django 2.1.2 on 2019-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20190425_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='stat_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
