# Generated by Django 2.2 on 2019-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_house_raw_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='freeway_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='light_rail_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='medical_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='mrt_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='police_score',
            field=models.IntegerField(default=-1),
        ),
    ]
