# Generated by Django 2.2 on 2019-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20190511_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='light_rail_score',
        ),
        migrations.RemoveField(
            model_name='house',
            name='mrt_score',
        ),
        migrations.AddField(
            model_name='house',
            name='all_population_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='house',
            name='total_traffic_score',
            field=models.IntegerField(default=-1),
        ),
    ]
