# Generated by Django 2.2 on 2019-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20190513_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='all_population_score',
            new_name='population_score',
        ),
    ]
