# Generated by Django 2.2 on 2019-05-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20190513_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='total_traffic_score',
            new_name='light_rail_score',
        ),
        migrations.AddField(
            model_name='house',
            name='mrt_score',
            field=models.IntegerField(default=-1),
        ),
    ]
